Add basics
BlaBlaPrincess/WS-SpringBoot-SimpleJava pull request #1
Opened 2021-06-23 04:49 UTC by BlaBlaPrincess

2021-06-25 01:39 UTC, progressicu requested changes

2021-06-25 01:39 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/integers/IntegersAverage.java
> +@ConditionalOnProperty(name = "integers_counting_algorithms_presenter.average", havingValue = "true")
java конечно многословный язык, но это не значит что везде нужно что-то длинное писать. Упрости названия пропертей

2021-06-25 01:39 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/integers/IntegersMin.java
> +        return Arrays.stream(array).min(Integer::compareTo).orElseThrow(IllegalArgumentException::new);
В одну строку вызовы методов сложно воспринимать, так что давай сделаем что-то такое:
![image](https://user-images.githubusercontent.com/48092349/123354849-d2556a80-d5a7-11eb-8f68-d3eba6429b1d.png)
Это пример форматирования, а не того, что нужно написать

2021-06-25 01:39 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/presenters/ArrayCountingAlgorithmsPresenter.java
> +    private T[] array;
Бин хранит состояние. Зачем так делать? Можно было тогда это сделать и обычным классом, если это прям нужно

2021-06-25 01:39 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/digitsrepresentation/DigitsRepresentation.java
> +        var length = number == 0 ? 1 : (int)(Math.log10(number) + 1);
Если длина == 0, то зачем ты создаешь массив из одного элемента?

2021-06-25 01:39 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/runners/CommandLineRunnerImpl.java
> +package com.blablaprincess.springboot_simplejava.runners;
названия пакетов должны быть полностью в lowercase

2021-06-25 01:39 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/runners/CommandLineRunnerImpl.java
> +    public CommandLineRunnerImpl(ArrayCountingAlgorithmsPresenter<Integer> presenter) {
Как я понял в данном пр ты не использовал lombok. Но вообще можно было, т.к. отдельно в пр выносить lombok было бы лишне
Ну да ладно

2021-06-25 01:39 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/runners/CommandLineRunnerImpl.java
> +        var scanner = new Scanner(System.in);
try with resources

2021-06-25 01:39 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/runners/CommandLineRunnerImpl.java
> +            var intArray = DigitsRepresentation.getDigitsArray(number);
А почему бы тебе не сделать, чтобы данный массив сразу возвращал в нужно виде значение. Т.е. чтобы строчка ниже не понадобилась

2021-06-25 01:39 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/arraycounting/integers/IntegersAverageTests.java
> +        Integer[] set = {1, 2, 3, 4, 10};
Комменты //Arrange, //Act, //Assert

2021-06-25 01:39 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/arraycounting/integers/IntegersAverageTests.java
> +    void count_PositiveSet_4() {
Методы в camelCase должны быть

2021-06-25 01:39 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/arraycounting/integers/IntegersAverageTests.java
> +        double result = new IntegersAverage().count(set);
Несколько тестовых кейсов и ты каждый раз создаешь новый объект. Вынеси это в поле тестового класса и всё будет также хорошо работать, но будет проще

2021-06-25 01:39 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/digitsrepresentation/DigitsRepresentationTests.java
> +    void getDigitsArray_SingleDigit_Equals(){
Чем этот тест отличается от теста ниже? Как по мне одно и тоже

2021-06-25 01:39 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/presenters/ArrayCountingAlgorithmsPresenter.java
> +        builder.append(String.format("Counting algorithms for %s", array.getClass().getSimpleName()));
Не совсем понял специфику метода. Ты пишешь, что вот столько есть алгоритмов для данного типа массива, но по факту выводишь просто кол-во алгоритмов без всяких проверок. Немного не стыкуется

2021-06-25 01:39 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/presenters/ArrayCountingAlgorithmsPresenter.java
> +    public ArrayCountingAlgorithmsPresenter<T> withSeparator(String separator) {
А ты уверен, что тебе этот метод нужен?

2021-06-25 01:39 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/runners/CommandLineRunnerImpl.java
> +        presenter.setup(new Integer[]{})
И для чего тебе этот setup, если ты потом заменяешь этот массив?

2021-06-25 03:21 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/runners/CommandLineRunnerImpl.java
> +    public CommandLineRunnerImpl(ArrayCountingAlgorithmsPresenter<Integer> presenter) {
Нет, не использовал, потом добавлю. В принципе, учитывая что это учебный проект, ничего страшного в вынесении lombok'a в пр не вижу

2021-06-25 03:23 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/runners/CommandLineRunnerImpl.java
> +            var intArray = DigitsRepresentation.getDigitsArray(number);
Чтобы не подгонять класс DigitsRepresentation под конкретную задачу, я предположил, что int используется чаще, чем Integer, поэтому он возвращает int[]

2021-06-25 03:25 UTC, BlaBlaPrincess commented on src/test/java/com/blablaprincess/springboot_simplejava/business/arraycounting/integers/IntegersAverageTests.java
> +        Integer[] set = {1, 2, 3, 4, 10};
Да, мы это обсудили на предыдущем занятии, добавлю в следующем пр, в том числе и тест на поднятия контекста починю, тк сейчас он не прогоняется из за запуска CommanLineRunner'а

2021-06-25 03:28 UTC, BlaBlaPrincess commented on src/test/java/com/blablaprincess/springboot_simplejava/business/arraycounting/integers/IntegersAverageTests.java
> +    void count_PositiveSet_4() {
Насколько знаю, для тестов другие конвенции, ориентировался на это: 
https://stackoverflow.com/questions/155436/unit-test-naming-best-practices
https://medium.com/@stefanovskyi/unit-test-naming-conventions-dd9208eadbea

2021-06-25 03:30 UTC, BlaBlaPrincess commented on src/test/java/com/blablaprincess/springboot_simplejava/business/digitsrepresentation/DigitsRepresentationTests.java
> +    void getDigitsArray_SingleDigit_Equals(){
Для нуля отдельная логика, поэтому кейс с 0 тестируется отдельно

2021-06-25 03:36 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/runners/CommandLineRunnerImpl.java
> +        presenter.setup(new Integer[]{})
Для вызова `withAlgorithmsCount()`, а именно для `builder.append(String.format("Counting algorithms for %s", array.getClass().getSimpleName()));` чтобы вывести тип массива, так в рантайме из дженерика я не могу это получить

2021-06-25 03:37 UTC, BlaBlaPrincess commented on src/test/java/com/blablaprincess/springboot_simplejava/business/arraycounting/integers/IntegersAverageTests.java
> +        double result = new IntegersAverage().count(set);
Хорошо

2021-06-25 03:38 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/presenters/ArrayCountingAlgorithmsPresenter.java
> +        builder.append(String.format("Counting algorithms for %s", array.getClass().getSimpleName()));
Не совсем понял. Метод, действительно, просто выводит количество алгоритмов, он так и задумывался, о каких проверках речь?

2021-06-25 03:38 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/presenters/ArrayCountingAlgorithmsPresenter.java
> +    public ArrayCountingAlgorithmsPresenter<T> withSeparator(String separator) {
Нет, не нужен, уберу

2021-06-25 03:39 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/business/digitsrepresentation/DigitsRepresentation.java
> +        var length = number == 0 ? 1 : (int)(Math.log10(number) + 1);
Немного не так: если число (не длина) 0, то длина массива 1. 0 обрабатывается отдельно, так как от него нельзя брать log. Хотя, лучше, я просто заменю на return 0;

2021-06-25 03:53 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/integers/IntegersAverage.java
> +@ConditionalOnProperty(name = "integers_counting_algorithms_presenter.average", havingValue = "true")
Хорошо. Такой момент: мне нужно отписывать "хорошо" под теми пунктами, где я все понял?) есть такая практика?)

2021-06-25 03:56 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/integers/IntegersMin.java
> +        return Arrays.stream(array).min(Integer::compareTo).orElseThrow(IllegalArgumentException::new);
Исправлю

2021-06-25 04:00 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/runners/CommandLineRunnerImpl.java
> +        var scanner = new Scanner(System.in);
Я не понял)

2021-06-25 04:27 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/runners/CommandLineRunnerImpl.java
> +package com.blablaprincess.springboot_simplejava.runners;
Это lowercase, где символ `-` заменен на `_` , согласно https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

2021-06-25 04:50 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/integers/IntegersAverage.java
> +@ConditionalOnProperty(name = "integers_counting_algorithms_presenter.average", havingValue = "true")
Как хочешь. Можешь писать, можешь не писать. Главное, чтобы понял и в итоге пр был хороший

2021-06-25 04:54 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/digitsrepresentation/DigitsRepresentation.java
> +        var length = number == 0 ? 1 : (int)(Math.log10(number) + 1);
А, ну да, поторопился. Извини

2021-06-25 04:56 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/runners/CommandLineRunnerImpl.java
> +package com.blablaprincess.springboot_simplejava.runners;
Ничего себе. Как-то ни разу не замечал это. Просто в какую библиотеку не загляни, так там полностью lowercase, т.е. что-то типа springbootsimplejava

2021-06-25 05:09 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/runners/CommandLineRunnerImpl.java
> +            var intArray = DigitsRepresentation.getDigitsArray(number);
Делать всё универсальным не всегда полезно. Т.к. некоторые вещи просто редко пригождаются. Так что лучше сделать здесь как можно лучше в данном варианте, а если еще где-то пригодится, то тогда только править

2021-06-25 05:16 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/arraycounting/integers/IntegersAverageTests.java
> +    void count_PositiveSet_4() {
Смотря где. В примере со stackoverflow там и метод с большой буквы.
Но вообще [вот](https://junit.org/junit5/docs/current/user-guide/#writing-tests-classes-and-methods), например. Это используемый в большинстве случаев фрэймворк под тесты и даже в примерах там написано в camelCase.

Да и как бы не все стандарты нужно принимать, т.к. некоторые просто неудобны. Личное мнение: так себе смотреть, когда в коде всё в camelCase, а тесты так выделяются

2021-06-25 05:16 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/digitsrepresentation/DigitsRepresentationTests.java
> +    void getDigitsArray_SingleDigit_Equals(){
Это я уже понял, всё правильно, отлично

2021-06-25 05:22 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/presenters/ArrayCountingAlgorithmsPresenter.java
> +        builder.append(String.format("Counting algorithms for %s", array.getClass().getSimpleName()));
Смотри. Ты у массива получаешь название класса и пишешь типа "кол-во алгоритмов для int[]". Т.е. по смыслу могло бы быть и double[] вместо int[]. Т.е. когда пишешь для "какой-то типа", то предполагается, что возможно будет какая-то разница между выводами.
Но это больше придирка, так что можешь не править это

2021-06-25 05:23 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/runners/CommandLineRunnerImpl.java
> +        presenter.setup(new Integer[]{})
А нужен ли тебе этот тип? Почему нельзя просто вывести кол-во алгоритмов, что по факту у тебя метод и делает

2021-06-26 07:05 UTC, BlaBlaPrincess commented
Fix conversations items

2021-06-26 11:02 UTC, progressicu reviewed
Форматирование не забудь поправить. А то в некоторых местах поплыло

2021-06-26 11:02 UTC, progressicu commented on .gitignore
> +.idea/**/workspace.xml
А для чего тебе понадобились файлы ниже в Git-е из папки .idea? Обычно просто всю папку игнорят, да и всё

2021-06-26 11:02 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/common/IntUtils.java
> +public class IntUtils {
Можно было и в DigitsRepresentation просто private методом, т.к. больше нигде не используется. Плодить классы не всегда нужно

2021-06-26 11:02 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/arraycounting/integers/IntegersAverageTests.java
> +        result = new IntegersAverage().count(set);
Даже не подумал бы, что так можно догадаться сделать...

Я имел ввиду, что нужно было вынести, например,  IntegersAverage, а не типы переменных.
Т.к. допустим мы будем запускать тесты паралельно (это возможно, просто не делаем по определенным причинам, но всё же), то будут непредсказуемые результаты, но а если вынести сам тестируемый класс, то как он не хранит состояние, то будет всё ок, даже если паралельно всё пойдет.

Это как бы не причина, а следствие твоего решения. Но а вообще типы нет смысла выносить - только общие неизменяемые переменные, чтобы облегчить понимание каждого теста. Да и вообще  каждый тест должен быть независимым от других

2021-06-26 11:02 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/arraycounting/integers/IntegersAverageTests.java
> +    Integer[] set;
Делай поля private, пожалуйста, даже в тестах

2021-06-26 11:02 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/presenters/formatters/ArrayCountingAlgorithmsPresenterDataJsonFormatter.java
> +public class ArrayCountingAlgorithmsPresenterDataJsonFormatter
Такой вопрос, а для чего это? Типа зачем это json представление, требования же не было

2021-06-26 11:02 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/integers/IntegersMin.java
> +@ConditionalOnProperty(name = "int_ca.min", havingValue = "true")
Как-то не складываются у тебя с наименованиями. То длинные, то слишком короткие
Почему не назвать, допустим, int.calculator.min.enabled=true, а  ca_presenter_formatter -> calculators.result.format=json

2021-06-26 11:02 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/presenters/ArrayCountingAlgorithmsPresenter.java
> +    public String present(T[] array) {
Обычно public методы вверху, а все подчиненные методы ниже один за другим

2021-06-26 11:02 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/presenters/ArrayCountingAlgorithmsPresenter.java
> +    private ArrayCountingAlgorithmsPresenterData getInfo(T[] array) {
Толку от этого метода если выполняет одно небольшое действие? Если так выносить, то классы разрастутся до громадных размеров.
Можно было создание этой переменной сделать в present(array), а потом следующей строкой вызвать formatter.format

2021-06-26 11:02 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/presenters/ArrayCountingAlgorithmsPresenterData.java
> +public class ArrayCountingAlgorithmsPresenterData {
Что-то до меня не доходит польза этого класса. Опять лишний класс, почему нельзя вместо него просто использовать сразу Map?

2021-06-26 11:02 UTC, progressicu commented on pom.xml
> +        <dependency>
И для чего тебе эта зависимость здесь, раз не используешь?

2021-06-26 11:59 UTC, BlaBlaPrincess commented on .gitignore
> +.idea/**/workspace.xml
Jet-brains [указывают](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839) не добавлять папку .idea целиком в .gitignore

2021-06-26 12:02 UTC, BlaBlaPrincess commented on src/test/java/com/blablaprincess/springboot_simplejava/business/arraycounting/integers/IntegersAverageTests.java
> +        result = new IntegersAverage().count(set);
Ох, да xd
Я подумал, что это практика больше к оформлению, теперь понял

2021-06-26 12:06 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/common/IntUtils.java
> +public class IntUtils {
Но ведь это нарушение SRP? Получать длину int'а не относится к задаче класса DigitsRepresentation. Я понимаю, что есть проблема overengineering'а, но, мне кажется, не здесь.

2021-06-26 12:10 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/presenters/formatters/ArrayCountingAlgorithmsPresenterDataJsonFormatter.java
> +public class ArrayCountingAlgorithmsPresenterDataJsonFormatter
Было доп. задание инжектить способ вывода результата. Хотя я внедряю не способ, а формат,- это была проба с задачи полегче. Способ добавлю позже

2021-06-26 12:16 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/presenters/ArrayCountingAlgorithmsPresenter.java
> +    public String present(T[] array) {
Я руководствуюсь такой логикой: если метод А использует метод Б, то метод Б должен быть объявлен раньше метода А, для того чтобы читать файл сверху вниз

2021-06-26 12:21 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/presenters/ArrayCountingAlgorithmsPresenterData.java
> +public class ArrayCountingAlgorithmsPresenterData {
Точка расширения

2021-06-26 12:27 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/presenters/ArrayCountingAlgorithmsPresenter.java
> +    private ArrayCountingAlgorithmsPresenterData getInfo(T[] array) {
Так или иначе, методы делают разные вещи, пусть один из них и однострочный; и далее, если потребуется, с методами можно делать что угодно, не меняя их сигнатуры
Да и в целом, ведь чем меньше метод, тем лучше? Декомпозиция + повышение читабельности

2021-06-26 12:28 UTC, BlaBlaPrincess commented on src/test/java/com/blablaprincess/springboot_simplejava/business/arraycounting/integers/IntegersAverageTests.java
> +    Integer[] set;
Хорошо

2021-06-26 12:29 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/integers/IntegersMin.java
> +@ConditionalOnProperty(name = "int_ca.min", havingValue = "true")
Еще подумаю над наименованиями, теперь есть на что ориентироваться

2021-06-26 12:32 UTC, BlaBlaPrincess commented on pom.xml
> +        <dependency>
Использую, в ней jupiter и springframework.test

2021-06-27 01:04 UTC, progressicu commented on .gitignore
> +.idea/**/workspace.xml
Ну не знаю, как по мне это лишне. Каждый настраивает проект под себя, а в большинстве случаев оно само настраивается одинаково у каждого, так что эти файлы оказываются лишними
Ну да ладно, пусть будет пока.

2021-06-27 01:04 UTC, progressicu commented on pom.xml
> +        <dependency>
Ты возможно не понял, но я указывал на google.guava

2021-06-27 01:04 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/presenters/ArrayCountingAlgorithmsPresenter.java
> +    public String present(T[] array) {
Возможно это и нужно в некоторых ЯП, но не здесь. Здесь мы открываем класс, сразу видим какой-то основной метод, потом видим, что он использует другой, листаем ниже и т.д. Т.е. мы читаем класс как обычный текст сверху вниз

2021-06-27 01:04 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/presenters/ArrayCountingAlgorithmsPresenter.java
> +    private ArrayCountingAlgorithmsPresenterData getInfo(T[] array) {
Не совсем. Декомпозировать можно многое, хоть это и кажется, что повышается читабельность, но на самом деле это ухудшает, т.к. появляется много методов, которые по факту ничего сложного не делают и если написать в том же методе, где вызывались, то будет такой же эффект.

Метод present представляет твои данные, а что он для этого делает - использующим классам без разницы. Пусть он создает классы, пусть он пишет в файл, главное, чтобы суть метода выполнялась. Иногда действиетльно стоит выносить создание класса, но когда у тебя что-то типа такого (т.е. большой объект)
![image](https://user-images.githubusercontent.com/48092349/123529530-766c1c80-d734-11eb-9422-ef1980b83a57.png)
или такое
![image](https://user-images.githubusercontent.com/48092349/123529545-ac110580-d734-11eb-910c-e1b1c0ccc970.png)
Т.е. это просто маппинг одних полей в другей, логики также нету, но это просто большой объем и в вызывающем методе это просто затмевает основную логику, которой по факту не так уж и много было

2021-06-27 01:04 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/presenters/ArrayCountingAlgorithmsPresenter.java
> +    private ArrayCountingAlgorithmsPresenterData getInfo(T[] array) {
Вот представь, что если бы я еще бы этот метод разбил. У меня бы тогда получилось 6 методов в последнем случае и 4 в первом. А если представить, что в классе и так немало методов, то это всё будет наоборот ухудшать читабельность

2021-06-27 01:04 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/presenters/ArrayCountingAlgorithmsPresenterData.java
> +public class ArrayCountingAlgorithmsPresenterData {
Расширения чего? Если я правильно понял, то не нужно думать о возможном будущем расширении, если пока это не планируется, это ухудшит читабельность и это усложняет код

2021-06-27 01:04 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/presenters/formatters/ArrayCountingAlgorithmsPresenterDataJsonFormatter.java
> +public class ArrayCountingAlgorithmsPresenterDataJsonFormatter
Ну если такое было, то тогда вопросов нет, всё норм.

2021-06-27 01:04 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/common/IntUtils.java
> +public class IntUtils {
Стандарты правила есть для того, чтобы программа стала легче на восприятие, поддержание и т.п. Всё нельзя подогнать под правила, т.к. это иного наоборот ухудшает ситуацию. 

Хотя в данном случае этого даже не касается и всё было бы норм. У тебя  DigitsRepresentation отвечает за "представление цифр", и получение длины для этого вполне себя оправдывает, если бы это было private методом. Т.е. в данном случае именно private разрешает проблему, о которой ты говоришь. 

А вот если бы это был public метод в DigitsRepresentation, то была бы небольшая проблема, т.к. класс стал бы отвечать за хар-ки числа, а также за представление

Т.е. в крайности тоже не всегда нужно входить. На простых вещах как эти все запоминают SRP и т.п., что это хорошо. А вот как доходит до больших проектов, то всё пишут в одном классе, либо дробят этот функционал на 15 классов и оба варианта ухудшают ситуацию. Нужно знать меру и включать голову, что правила придуманы не просто так и иногда лучше из них выйти, чтобы следовать  их смыслу

2021-06-27 08:34 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/common/IntUtils.java
> +public class IntUtils {
> Стандарты правила есть для того, чтобы программа стала легче на восприятие, поддержание и т.п. Всё нельзя подогнать под правила, т.к. это иного наоборот ухудшает ситуацию.

Конечно, полностью согласен. Любые правила нужно применять с умом, и из любых правил существуют исключения. Делать что то _просто потому что так нужно_ нельзя, нужно понимать зачем

В данном случае, я не согласен, что вынос логики в отдельный класс излишен
Пусть метод и будет private, но как только мы добавляем новую логику, где также необходимо получать длину числа: мы или выносим получение длины в отдельный класс, как это сделано сейчас / или нарушаем DRY, причем нарушаем неоправданно;

Плюс, если это private метод, то возникают проблемы с его тестированием

> Т.е. в крайности тоже не всегда нужно входить.

Крайности это плохо, но данный случай я крайним не считаю

> А вот как доходит до больших проектов, то всё пишут в одном классе, либо дробят этот функционал на 15 классов и оба варианта ухудшают ситуацию.

Все таки, если мы говорим про класс, который удалось раздробить на 15, _пусть это гиперболизированный пример, но все же,_ скорее всего это что то из доменной логики, где переиспользование этих 15 классов сомнительно в силу высокой сцепленности; здесь же речь про utility для работы с int'ом

2021-06-27 08:42 UTC, BlaBlaPrincess commented on pom.xml
> +        <dependency>
Да, не понял, в conversation'е показываются строки 36 - 39, guava 40 и далее
Зависимость не нужна, убрал

2021-06-27 08:42 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/common/IntUtils.java
> +public class IntUtils {
Ладно, не буду настаивать. Всё же у каждого своё мнение на этот счет и это не настолько критично в данном случае. 
Просто как часто тебе приходилось считать длину числа, на сколько возможно это пригодится в будущем. Просто я лучше в будущем вынесу в отдельный класс, когда это действительно будет необходимо, чем сейчас

2021-06-27 08:53 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/presenters/ArrayCountingAlgorithmsPresenterData.java
> +public class ArrayCountingAlgorithmsPresenterData {
Да, ты все верно понял, я о будущем расширении _(потенциальном)_

Не совсем понимаю, почему это плохо: обернув Map в класс, не нужно будет менять зависимые классы, если появится необходимость добавить другие поля в ArrayCountingAlgorithmsPresenterData. Класс обертка очень упрощает расширение в дальнейшем. В таком ключе нельзя думать обо всем, но некоторые точки расширения должны быть заложены, в том числе для обратной совместимости между версиями пакета

Да, я говорю о _потенциальном_ расширении, **зная**, что его здесь не будет, но почему не приучать себя сразу писать правильно? В моем понимании, не важен размер проекта, нужно все равно следовать общим парадигмам до тех пор, пока позволяют время и дедлайны, а в данном случае позволяют

2021-06-27 09:16 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/presenters/ArrayCountingAlgorithmsPresenter.java
> +    private ArrayCountingAlgorithmsPresenterData getInfo(T[] array) {
Я еще подумал, да, ты прав
Единственное, мыслю с другой стороны, чем ты предлагаешь: это законченный класс, где я знаю, что private метод переиспользоваться не будет + в данном случае, это не повышает читабельность, а так как редактирование внутренней логики класса не меняет его интерфейс, то здесь и сейчас я могу объединить эти методы, а после, если понадобится, вынести метод **без осложнений**

> Вот представь, что если бы я еще бы этот метод разбил. У меня бы тогда получилось 6 методов в последнем случае и 4 в первом. А если представить, что в классе и так немало методов, то это всё будет наоборот ухудшать читабельность

А я бы вынес) Зачем, читающему код, разбирать что именно получается на выходе из билдера, если можно это описать в названии методов? И, раз IDEA почти стандарт, кинул бы эти методы под //region .. //endregion

2021-06-28 00:51 UTC, BlaBlaPrincess commented
В рамках pr лучше писать отдельные коммиты, отменяющие изменения / или дропать коммиты и делать force push?

2021-06-29 04:46 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/presenters/ArrayCountingAlgorithmsPresenter.java
> +    private ArrayCountingAlgorithmsPresenterData getInfo(T[] array) {
Ну вот что-то такое я имел ввиду.

Вот именно, что ему не нужно разбираться и он в общих чертах понял, что на выходе получим какой-то reportMessageDto и хватит. А именно с region так себе практика - в пр её не заиспользуешь, только излишне нагружает код (не всегда конечно)

2021-06-29 04:53 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/presenters/ArrayCountingAlgorithmsPresenterData.java
> +public class ArrayCountingAlgorithmsPresenterData {
Чем она **очень** упрощает? Но я не буду настаивать, т.к. этот вариант имеет право на жизнь, так что здесь всё ок.

Насчет **очень** упрощает. Думают о будущем в основном на уровне иерархии, структуры, сервисов, т.к. вот это сложно переделать, а вынести параметры не проблема, но это действительно имеет место быть в некоторых местах, просто в данном случае я не увидел данный случай для меня, но у каждого своё мнение, так что всё хорошо - не правь

2021-06-29 04:54 UTC, progressicu commented
> В рамках pr лучше делать новые коммиты, отменяющие изменения / или дропать старые коммиты и делать force push?

Я всегда делаю новые коммиты, т.к. сохраняется история и можно всё отследить.

2021-06-29 04:54 UTC, progressicu approved these changes

2021-06-29 05:33 UTC, merged

2021-06-29 06:48 UTC, BlaBlaPrincess commented on .gitignore
> +.idea/**/workspace.xml
Подумал, тебе может быть интересно

Сейчас делал дз по type script, и пришлось немного настроить ide. Потрогал на практике, для чего может быть полезно пушить .idea:

- первое, для расшаривания конфигураций запуска, они лежат в .idea (не обязательно, но по умолчанию)

![Безымянный](https://user-images.githubusercontent.com/66216611/123747515-669c3600-d8f6-11eb-9d08-56cd17310cdb.png)

- второе, для расшаривания меток директорий: excluded/tests/resources root, эти указания также находятся в .idea

![Безымянный1](https://user-images.githubusercontent.com/66216611/123747905-ddd1ca00-d8f6-11eb-9554-3a71685d8e4e.png)

Например: файлы в excluded директориях (отмечены оранжевым) не анализируются ide. А, учитывая, что у меня в папке dist лежат транспилированные в js файлы, то такая метка будет весьма кстати. И у любого, кто сделает git clone, эта папка также будет игнорироваться

2021-06-30 04:09 UTC, progressicu commented on .gitignore
> +.idea/**/workspace.xml
С клонирование js проектов не сталкивался, только для себя пока делаю, так что тут ничего не скажу.
Кроме того, что через webStorm прекрасно распознает скрипты, которые указаны в конфигах и делает тебе подсказки тебе по ним. 

Но, например, с java и maven всё отлично автоматически импортируется/распознается и без этих файлов. 
Делиться конфигурациями запуска - довольно сомнительный аргумент т.к., мы можем дебагом подключаться к серверам и в большинстве случаев это не надо другим. Также в конфигурациях остаются запуски тестов.
Насчет меток директорий - также всё автоматически делается, как только клонирую проект.

Т.е. за 1,5 года мне не пришлось, что-то вручную делать с конфигурацией IDEA для определенного проекта. Хотя много чего делали и много версий прошло, как IDEA, так и maven/java

Но я не скажу, что это плохо и не надо. Возможно встречусь с такой ситуацией и тогда я сделаю это (ну или придется, если всей компанией перейдем), т.к. логично, что для этого что-то придумали и я вспомню про твой коммент. Но мне пока это не надо, есть и другие проблемы поважнее