Add rest controller
BlaBlaPrincess/WS-SpringBoot-SimpleJava pull request #2
Opened 2021-07-03 13:35 UTC by BlaBlaPrincess

2021-07-04 07:37 UTC, progressicu commented
Зачем выкладывать ссылку, если еще пр не готов? Может ты потом изменишь, что-то кардинально, т.к. что-то не подходит (такое бывает иногда)
Когда будет готово, тогда и выкладывай, чтобы не сбивать проверяющих

2021-07-14 08:34 UTC, progressicu requested changes
А где интеграционные тесты?

2021-07-14 08:34 UTC, progressicu commented on pom.xml
> +		<dependency>
Эта и последняя зависимость лишняя. Это уже всё есть в подключенном стартере https://mvnrepository.com/artifact/io.springfox/springfox-boot-starter/3.0.0

2021-07-14 08:34 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/arraycounting/presenters/ArrayCountingAlgorithmsPresenterService.java
> +        return ArrayCountingAlgorithmsPresenterDto.builder()
Ну и для чего builder, если всего одно поле? Можно было просто через конструктор создать

2021-07-14 08:34 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/common/utils/ArrayUtils.java
> +    public static <T> void ValidateArrayNotEmpty(T[] array) {
С маленькой буквы

2021-07-14 08:34 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/ExceptionsHandler.java
> +    public ModelAndView handleServletException
Не думаешь, что это как-то сложнее того, что я показал? 
И представь, что это фронту еще обрабатывать - т.е. доставать данные из header-ов, когда можно было из тела (для него больше методов, на сколько я знаю)

2021-07-14 08:34 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/ExceptionsHandler.java
> +    public ModelAndView handleServletException
Я не только про сам метод, а даже про сам класс в принципе

2021-07-14 08:34 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/RestException.java
> +    protected RestException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace) {
И для чего тебе этот конструктор? Допустим выше 3 мы можем использовать, а вот этот я ни разу не видел хоть где-то. Так что думаю можно убрать, только лишний код

2021-07-14 08:34 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/controllers/CountsController.java
> +    public RedirectView redirectCountsForIntToInteger(
Интересно. Не буду говорить, что этого не было в задании и вряд ли ты это будешь делать на spring, т.к. обычно для этого тот же nginx можно заиспользовать, но пусть уже будет

2021-07-14 08:34 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/arraycounting/integers/IntegersAverageTests.java
> +class IntegersAverageTests {
Как по мне - усложнил тесты для понимания. 
Под каждый тест теперь нужно думать, какой интерфейс подсунуть, создавать различные переменные - функции. В тестах копипаста иногда проще смотрится и делается.
И редко когда получается, что можно на одном методе сделать столько проверок. Обычно в arrange по разному мокаются объекты, поэтому описать в таком стиле становится еще сложнее. А если будет, что-то в одном стиле, что-то в другом и еще пару стилей напридумаем, то будет сложно смотреть и писать тесты
 
В данном случае проще было один ParameterizedTest + Test, в котором кидается исключение. Представь у тебя будут везде тесты типа метод = {AAA}, и тут ты встречаешь что-то такое. Проверяющим придется потратить больше времени, чтобы разобраться, что где означает, где какие методы (вряд ли в дальнейшем они будут такие простые).

2021-07-14 08:34 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/rest/controllers/CountsControllerTest.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
Можно было и без этого

2021-07-14 08:34 UTC, progressicu commented on src/test/resources/junit-platform.properties
> +junit.jupiter.execution.parallel.enabled = true
Лучше убрать этот файл. Зачем тебе эти настройки?

2021-07-19 05:49 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/ExceptionsHandler.java
> +    public ModelAndView handleServletException
Заменил header'ы на Dto.
Касательно сложности класса: мне просто было интересно прикрутить стандартную обработку исключений из spring'а, чтобы получать response коды для "дефолтных" исключений, + разобраться в том, как это работает изнутри, все таки, первоочередно, это учебный проект.
Выбирая между тем, как делают обычно, и как сделано, то я бы рассудил так: первый вариант подходит для больших решений, так как в нем выше читабельность; второй для маленьких, так как он не засоряет обработчик исключениями по типу HttpMediaTypeNotAcceptableException.

2021-07-19 06:00 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/RestException.java
> +    protected RestException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace) {
Назначение этого класса в том, чтобы быть суперклассом для исключений указанного слоя, а значит, он должен предоставлять те же конструкторы что и RuntimeException

2021-07-19 06:22 UTC, BlaBlaPrincess commented on src/test/java/com/blablaprincess/springboot_simplejava/business/arraycounting/integers/IntegersAverageTests.java
> +class IntegersAverageTests {
Согласен, тесты стали сложнее для понимания "как код", но, с другой стороны, они стали проще для понимания "как документация". Пока пробую разное, обязательно гляну статью, что ты кинул в тг.
В том виде, в котором тесты находятся сейчас, как мне кажется, выигрыш от упрощения больше, чем проигрыш от усложнения, хотя в классах с mock'ами где-то на грани. Скидывал Владу вариант с IntegersAverage, ему понравилось.

2021-07-19 06:24 UTC, BlaBlaPrincess commented on src/test/resources/junit-platform.properties
> +junit.jupiter.execution.parallel.enabled = true
Тестируется быстрее

2021-07-19 06:31 UTC, BlaBlaPrincess commented on src/test/java/com/blablaprincess/springboot_simplejava/rest/controllers/CountsControllerTest.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
Тогда придется делать метод getCases static'ом со всеми вытекающими

2021-07-19 06:31 UTC, BlaBlaPrincess commented on src/test/java/com/blablaprincess/springboot_simplejava/rest/controllers/CountsControllerTest.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
В IndexController'е убрал

2021-07-23 05:17 UTC, progressicu commented on pom.xml
> +			<artifactId>springfox-boot-starter</artifactId>
Этот starter итак тащит springfox-swagger2, springfox-swagger-ui. Так что как отдельные зависимости они не нужны

2021-07-23 05:17 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/ExceptionsHandler.java
> +                .path     (request.getRequestURI())
Что с форматированием?

2021-07-23 05:17 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/ExceptionsHandler.java
> +    public ErrorDto handleServletException
До меня всё равно не дошло зачем тебе нужен был DefaultHandlerExceptionResolver, если всё равно всё свелось к  @ExceptionHandler. Из DefaultHandlerExceptionResolver используешь только sendServerError, в котором отвечаешь 500. 
В общем даже для учебного проекта что-то непонятное получилось. Да, разобраться это хорошо, но не таким кодом

2021-07-23 05:17 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/RestException.java
> +    protected RestException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace) {
Все равно не понял для чего тебе последний конструктор. И что, что он суперкласс. Это тебя не обязывает переопределять все конструкторы

2021-07-23 05:17 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/common/ProvidingSettersResponseWrapper.java
> +public class ProvidingSettersResponseWrapper extends HttpServletResponseWrapper {
И для чего тебе это? Проще уже вручную проставить этот статус

2021-07-23 05:17 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/arraycounting/integers/IntegersAverageTests.java
> +class IntegersAverageTests {
Ну как документация да, это действительно удобно, что снизу есть типа UC. Просто редко, где такое получится сделать, как по мне, и тем более так просто описать эти кейсы

2021-07-23 05:17 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/rest/ExceptionsHandlerMvcIT.java
> +@Execution(ExecutionMode.SAME_THREAD)
А для чего ты так делаешь?

2021-07-23 05:17 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/rest/controllers/CountsControllerMvcIT.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
Вроде уже писал, но ты уверен, что оно тебе надо?

2021-07-23 05:17 UTC, progressicu commented on src/test/resources/junit-platform.properties
> +junit.jupiter.execution.parallel.enabled = true
Ну пока да, а что делать, когда пойдут тесты с БД? Там паралельно с одной таблицей не получится тестировать

2021-07-23 06:39 UTC, BlaBlaPrincess commented on src/test/resources/junit-platform.properties
> +junit.jupiter.execution.parallel.enabled = true
Есть аннотация на класс, которая указывает тестировать однопоточно, у меня она стоит на интеграционных тестах

2021-07-23 06:45 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/ExceptionsHandler.java
> +                .path     (request.getRequestURI())
Выравнивание по параметрам функции

![1](https://user-images.githubusercontent.com/66216611/126746332-833675c4-871c-40ae-8667-e1f386de2a16.png)

2021-07-23 06:56 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/ExceptionsHandler.java
> +    public ErrorDto handleServletException
Я использую `doResolveException` из `DefaultHandlerExceptionResolver`

![6](https://user-images.githubusercontent.com/66216611/126747194-a2cfce56-34d3-4744-94b9-9e470deb768c.png)
![4](https://user-images.githubusercontent.com/66216611/126746946-e3037373-7bed-405b-b574-296e7f04ffd5.png)

И если он возвращает _null_, то обращаюсь к map с бизнесовыми исключениями, если там нет искомого ключа, то возвращаю 500

![2](https://user-images.githubusercontent.com/66216611/126746551-15fd9718-ea10-4dcb-b8d8-35e402eda22d.png)

А `sendServerError` я уберу, он здесь не нужен, остался от экспериментов, моя ошибка

2021-07-23 06:59 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/common/ProvidingSettersResponseWrapper.java
> +public class ProvidingSettersResponseWrapper extends HttpServletResponseWrapper {
Мне нужно было, чтобы `send` методы ничего не делали, кроме установки статуса, тк именно они используются в `DefaultHandlerExceptionResolver`, см. [выше](https://github.com/BlaBlaPrincess/WS-SpringBoot-SimpleJava/pull/2#discussion_r675344384)

2021-07-23 07:00 UTC, BlaBlaPrincess commented on src/test/java/com/blablaprincess/springboot_simplejava/rest/controllers/CountsControllerMvcIT.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
Переписал этот тест

2021-07-23 07:04 UTC, BlaBlaPrincess commented on src/test/java/com/blablaprincess/springboot_simplejava/rest/controllers/CountsControllerMvcIT.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
Вообще, да, [нужно было](https://github.com/BlaBlaPrincess/WS-SpringBoot-SimpleJava/pull/2#discussion_r672020073), но я рассудил, что так лучше не делать

2021-07-23 07:05 UTC, BlaBlaPrincess commented on src/test/java/com/blablaprincess/springboot_simplejava/rest/ExceptionsHandlerMvcIT.java
> +@Execution(ExecutionMode.SAME_THREAD)
Mock'и плохо работают с многопоточными тестами

2021-07-23 07:19 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/RestException.java
> +    protected RestException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace) {
> И что, что он суперкласс.

Не важно, что он суперкласс, важно, что быть суперклассом его единственное назначение.
Он не должен скрывать что либо, так как это не его задача.

Я не знаю, для чего может быть использован этот конструктор, как и большинство других, но раз разработчики `RuntimeException` его предоставляют, то и я делаю то же самое, не просто так ведь он там находится

2021-07-23 08:22 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/RestException.java
> +    protected RestException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace) {
> Он не должен скрывать что либо, так как это не его задача
Ну и лишнего он не должен предоставлять, зачем это просто. Ну да ладно, не сильно влияет, так что пусть будет

2021-07-23 08:23 UTC, progressicu commented on src/test/resources/junit-platform.properties
> +junit.jupiter.execution.parallel.enabled = true
Теперь до меня дошло, что ты сделал. Тогда ок

2021-07-23 08:24 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/ExceptionsHandler.java
> +                .path     (request.getRequestURI())
А где ты такой взял стиль, просто мы вроде скидывали другое. Не говорю, что это плохо, просто привык к другому. Тут у каждого своё мнение всё равно будет

2021-07-23 08:30 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/ExceptionsHandler.java
> +    public ErrorDto handleServletException
Ладно, ок, пусть будет. 
Как по мне, всё равно чище и проще было написать с нуля эту обработку, так и будет сразу всем понятно, что мы тут действительно это исключение обработали, а не отдали на обработку spring-у, т.к. у него это не всегда информативно получается

2021-07-23 08:30 UTC, progressicu commented
В принципе всё ок. 
Много придирок, потому что отличается стиль написания, особенно тестов, ну и не привычно к этому

2021-07-23 08:32 UTC, progressicu approved these changes

2021-07-23 11:21 UTC, merged