Add saving history of controller calls
BlaBlaPrincess/WS-SpringBoot-SimpleJava pull request #4
Opened 2021-08-07 05:41 UTC by BlaBlaPrincess

2021-08-10 07:55 UTC, progressicu requested changes

2021-08-10 07:55 UTC, progressicu commented on pom.xml
> +		<dependency>
она уже должна быть в какой-то зависимости, так что зря здесь прописываешь

2021-08-10 07:55 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/controllercalls/ControllerCallsHistoryService.java
> +        Page<ControllerCallDescriptionEntity> page = repository.findAll(Pageable.ofSize(amount));
Просто pageable использовать - немного смутная затея. В данном случае не задается сортировка и тогда по идее возможно, например, что на второй странице получим часть результатов с первой

2021-08-10 07:55 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/controllercalls/ControllerCallDescriptionEntity.java
> +    private Date timestamp;
А почему не LocalDateTime? Было бы проще и лучше

2021-08-10 07:55 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/controllers/ControllerCallsHistoryController.java
> +            (Integer amount, Integer days, Integer hours, Integer minutes) {
Проще было сразу передать параметр Date from

2021-08-10 07:55 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/controllers/ControllerCallsHistoryController.java
> +            if (amount != null) {
Лучше так не делать.
У тебя получается данный метод отвечает за разные "пути" (ну если не судить по тому, что внутри сервиса). Да и как-то запутанно получилось, а толку от этого нет.
Тут лучше бы переделать либо сам метод сервиса, чтобы он в любом случае принимал все параметры, просто фильтры по некоторым отсутствовали. Либо отдельный хост на каждую ветвь

2021-08-10 07:55 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/controllercalls/ControllerCallsHistoryServiceTests.java
> +        service.getCalls();
Если метод что-то возвращает, то это должно быть проверено

2021-08-10 07:55 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/controllercalls/ControllerCallsHistoryServiceTests.java
> +        verify(repository, times(1)).findAll();
times(1) необязательно указывать. Итак по дефолту стоит

2021-08-10 07:55 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/controllercalls/ControllerCallsHistoryServiceTests.java
> +                .findByTimestampIsBetween(any(Date.class), any(Date.class));
Нужно проверять с какими именно датами вызвались методы. Вдруг порядок перепутан

2021-08-10 07:55 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/controllercalls/ControllerCallsHistoryServiceTests.java
> +                .thenReturn(new PageImpl<>(new ArrayList<>()));
Проще было мок Page вернуть

2021-08-10 07:55 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/controllercalls/ControllerCallDescriptionEntity.java
> +    public static class ControllerCallDescriptionEntityBuilder {
Если постоянно городить такие вещи, то проще через сервис. Там бы это заняло одну строчку. Всё равно всё сохранение только через бд идёт
Т.к. тебе только в бд нужны валидные записи, в тестах тебе, например,  вообще всё равно, что хранится в ответе

2021-08-10 07:55 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/controllercalls/ControllerCallDescriptionEntity.java
> +    public static class ControllerCallDescriptionEntityBuilder {
Да я знаю, что ответил в телеграме по другому. Но просто в сервисе более чище это смотрится, а вот проверка длины, лучше бы смотрилась здесь через аннотацию.
В следующий раз сразу с реальным примером задавай вопрос, чтобы такой ситуации не получилось

2021-08-11 04:43 UTC, BlaBlaPrincess commented on pom.xml
> +		<dependency>
![image](https://user-images.githubusercontent.com/66216611/128970724-2442dfeb-187e-4575-b815-213759820f15.png)

2021-08-11 04:46 UTC, BlaBlaPrincess commented on pom.xml
> +		<dependency>
Я не нашел, чтобы её кто-то дублировал

![image](https://user-images.githubusercontent.com/66216611/128970765-0484b20c-d0bb-421a-8e70-b184f46c8223.png)

И на диаграмме Confilcts/Duplicates этой зависимости тоже нет

![image](https://user-images.githubusercontent.com/66216611/128970989-3fd1fb37-d6df-46dc-af0c-5bb24c5c31d0.png)

2021-08-11 09:39 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/business/controllercalls/ControllerCallDescriptionEntity.java
> +    private Date timestamp;
В  java со временем все сложно)
Заменил на OffsetDateTime, чтобы учитывать временную зону

![image](https://user-images.githubusercontent.com/66216611/129006649-e96b1a81-0eee-46b6-897a-44433ff74970.png)

2021-08-11 09:39 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/controllers/ControllerCallsHistoryController.java
> +            (Integer amount, Integer days, Integer hours, Integer minutes) {
Заменил на Duration

2021-08-11 09:41 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/controllers/ControllerCallsHistoryController.java
> +            if (amount != null) {
Думаю, хорошим решением будет вынести ветвление в action

2021-08-11 10:49 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/controllers/ControllerCallsHistoryController.java
> +            (Integer amount, Integer days, Integer hours, Integer minutes) {
Поторопился с комментарием: Duration все равно про offset, ещё подумаю, как сделать удобнее

2021-08-12 06:54 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/controllercalls/ControllerCallDescriptionEntity.java
> +    private Date timestamp;
Ну не так уж и сложно. Смотря для чего, можно действительно OffsetDateTime или ZonedDateTime (что лучше наверное). А можно обычный LocalDateTime, но чтобы была договоренность с тем же фронтом, что отправляют дату в определенном поясе

2021-08-12 07:03 UTC, progressicu reviewed
Отпиши в телеграме, когда обновишь, чтобы я лишний раз не лазил сюда

2021-08-12 07:03 UTC, progressicu commented on pom.xml
> +		<dependency>
Ого, ничего себе. Хорошо, значит выпилили в новых версиях. Раньше куда не глянь, то она везде была

2021-08-12 07:03 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/controllers/ControllerCallsHistoryController.java
> +            (Integer amount, Integer days, Integer hours, Integer minutes) {
Удобнее всем - передавать сразу дату. На фронте/мобилке будет какой-нибудь календарь для выбора и это гораздо удобнее будет для всех

2021-08-12 09:21 UTC, progressicu commented on pom.xml
> +			<version>4.5.13</version>
Давай версии в проперти

2021-08-12 09:21 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/common/utils/LocalDateTimeUtilsImpl.java
> +public class LocalDateTimeUtilsImpl implements LocalDateTimeUtils {
Один вопрос - для чего? Ты не мог сразу вызвать у самого объекта это?
Лишний код

2021-08-12 09:21 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/common/utils/StringUtilsImpl.java
> +public class StringUtilsImpl implements StringUtils  {
Обычно утилитные классы пишем сразу в реализации, т.к. их реализацию смысла нет подменять.
Т.е. если вместо какого-то Action-а мы можем сделать другой Action, то тут в этом нет смысла

2021-08-12 09:21 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/controllercalls/ControllerCallsHistoryService.java
> +    public List<ControllerCallDescriptionEntity> getCalls() {
На методы ставь @Transactional. 
На методы чтения можно добавить readOnly=true

2021-08-12 09:21 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/common/utils/StringUtilsImplTests.java
> +    private static Stream<Arguments> cropByMaxLengthNotCroppedCases() {
Лишние кейсы.
Это логично, что если прошло 255 - 1, то пройдет и 255 / 2.
Аналогично про 255+1 и 255*2

И зачем вообще три разных числа. 
Хватило бы обозначить одно максимальное число и разобрать кейсы:
- Меньше него
- Равно ему
- Больше него 
И всё

2021-08-12 09:21 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/common/utils/StringUtilsImplTests.java
> +        String croppedInput = input.substring(0, half - 5) + "… … …" + input.substring(inputLength - half, inputLength - 1);
Не нужно использовать в коде тестов рабочий код.
Здесь нужно проверить, что сразу совпадает с нужной строкой.
Ну а для этого можно было просто выбрать задать пару строк разной длины, а не генерить их

2021-08-12 09:21 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/controllercalls/ControllerCallsHistoryServiceTests.java
> +        verify(repository).findAll(any(Pageable.class));
Нужно проверить, какой параметр пришёл

2021-08-12 09:21 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/controllercalls/ControllerCallsHistoryServiceTests.java
> +        verify(repository).findAll(any(Pageable.class));
Можно заиспользовать ArgumentCaptor

2021-08-12 09:21 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/rest/actions/ControllerCallsHistoryActionTests.java
> +    private final LocalDateTime to   = LocalDateTime.parse("2020-01-01T12:00");
Ты это вручную форматируешь так?

2021-08-12 09:21 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/common/persistence/UuidEntity.java
> +public class UuidEntity {
Тут нужно правильный equals и hashCode написать

2021-08-12 09:21 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/actions/ControllerCallsHistoryAction.java
> +public class ControllerCallsHistoryAction {
- Это не Service
- Вместо создания OffsetDateTime можно было его сразу принимать в контроллере
- много лишнего получается

По последнему пункту. 
- С Duration - выкинуть. Для данного кейса, сложно представить, что им будет кто-то пользоваться. Людям привычнее и проще задать две даты, чем считать сколько дней им нужно. А если всё таки нужно определенное кол-во дней, то это реализуется через фронт
- Для чего там много if. Это просто жуть какая-то для такого простого api. Мы же говорили используйте queryDsl, и сделайте PredicateBuilder (по желанию). Код упростится в разы. Чем если на каждый фильтр писать методы везде.  Если будет 20 фильтров (а такое может быть) и каждый может быть null, а другой нет, ты же не будешь столько методов писать. 
- Упрости, убери Action. В данном случае должно хватит вызова сервиса напрямую из контроллера. 
 
И кстати не принято, чтобы у Action-а было много методов

2021-08-12 09:21 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/controllercalls/ControllerCallsHistoryService.java
> +        Pageable request = PageRequest.of(0, amount, Sort.by("timestamp"));
Почему в одном случае ты задаешь порядок сортировки, а в другом нет?
Лучше указать сразу, что порядок сортировки DESC. Чтобы последние вызовы были в начале

2021-08-12 09:21 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/controllercalls/ControllerCallsHistoryService.java
> +    public List<ControllerCallDescriptionEntity> getLastCalls(int amount) {
А если захотят оставшиеся посмотреть? Им заново грузить весь список, но ещё дополнительно. Тут либо реализовывать нормально постарничный список, либо отдавать сразу всё. Посередние вариант для обычных людей - плохой вариант
Это хорошо для каких-то интеграций с другими системами, чтобы получать например последние события, но не в данном варианте

2021-08-12 15:42 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/actions/ControllerCallsHistoryAction.java
> +public class ControllerCallsHistoryAction {
- Я рассматриваю сервис как то, что вызывается из контроллера. С этой точки зрения, это сервис
- OffsetDateTime труднее парсить
- Лишнее уберу

2021-08-12 15:45 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/business/common/persistence/UuidEntity.java
> +public class UuidEntity {
Можно использовать lombok @EqualsAndHashCode?

2021-08-12 23:32 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/common/persistence/UuidEntity.java
> +public class UuidEntity {
неа

2021-08-12 23:32 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/actions/ControllerCallsHistoryAction.java
> +public class ControllerCallsHistoryAction {
- Так точно не правильно расценивать, что является сервисом. https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/stereotype/Service.html. 
- "OffsetDateTime труднее парсить". Ну не всё так легко бывает, но получше чем так. Либо везде LocalDateTime, либо везде OffsetDateTime/Instant/ZonedDateTime. Т.к. толку здесь от OffsetDateTime, если создаешь всегда с UTC

2021-08-13 04:15 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/actions/ControllerCallsHistoryAction.java
> +public class ControllerCallsHistoryAction {
Создаются записи в OffsetDateTime, с учетом временной зоны сервера. LocalDateTime встречается только в контроллере, который ищет по бд

2021-08-13 04:17 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/actions/ControllerCallsHistoryAction.java
> +public class ControllerCallsHistoryAction {
С точки зрения определения, которое ты скинул, это все еще сервис, нет?

2021-08-13 04:28 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/actions/ControllerCallsHistoryAction.java
> +public class ControllerCallsHistoryAction {
> Создаются записи в OffsetDateTime, с учетом временной зоны сервера. LocalDateTime встречается только в контроллере, который ищет по бд

Т.е. создаем записи в одной зоне, а когда приходит время от пользователя, то в UTC. Не находишь это немного странным?

2021-08-13 04:34 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/actions/ControllerCallsHistoryAction.java
> +public class ControllerCallsHistoryAction {
> С точки зрения определения, которое ты скинул, это все еще сервис, нет?
С точки зрения определения - нет. Но под это определение некоторые другие моменты не подходят. Так что тут я бы руководствовался "правилом", если не подходит под правило - то точно не `@Service`. Если 50/50, то тут самому можно решать.

Но я ставлю `@Service` только на сервисы работающие с бд. Не знаю почему, как то завелось с момента когда только изучал spring, так и не задумывался об этом. Т.к. по факту смысла особого не играет.

2021-08-13 04:36 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/common/persistence/UuidEntity.java
> +public class UuidEntity {
Т.к. помнишь я говорил про прокси, бд и т.п. 
В группу скидывал архив db.zip, там есть пример

2021-08-13 06:38 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/actions/ControllerCallsHistoryAction.java
> +public class ControllerCallsHistoryAction {
Заменил OffsetDateTime на LocalDateTime

2021-08-13 08:46 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/business/controllercalls/ControllerCallsHistoryService.java
> +    public List<ControllerCallDescriptionEntity> getLastCalls(int amount) {
Пока убрал Pageable, попозже к нему вернусь

2021-08-13 08:49 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/actions/ControllerCallsHistoryAction.java
> +public class ControllerCallsHistoryAction {
Не вспомнил про queryDsl, когда писал. Сделал через него

2021-08-13 08:52 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/business/common/utils/LocalDateTimeUtilsImpl.java
> +public class LocalDateTimeUtilsImpl implements LocalDateTimeUtils {
Ориентировался на [это](https://stackoverflow.com/questions/11887799/how-to-mock-new-date-in-java-using-mockito), нужно было замокать Date. В следующий раз посмотрю powerMock. Сейчас этот класс вообще убрал за ненадобностью

2021-08-13 08:55 UTC, BlaBlaPrincess commented on src/test/java/com/blablaprincess/springboot_simplejava/rest/actions/ControllerCallsHistoryActionTests.java
> +    private final LocalDateTime to   = LocalDateTime.parse("2020-01-01T12:00");
Не совсем понял вопрос, просто привожу строку к типу LocalDateTime

2021-08-13 13:46 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/common/persistence/UuidEntity.java
> +            return Objects.equals(this.id, that.id);
Будет ошибка, если так делать. Допустим это у тебя прокси, тогда возможно у него нет этого поля.
А вот если получить через getId(), то будет всё ок

2021-08-13 13:46 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/controllers/ControllerCallsHistoryController.java
> +        return controllerCallsHistoryService.getLastCalls(args);
Согласись же, что здесь, да и в сервисе теперь стало чище, меньше кода, да и просто понятнее

2021-08-13 13:46 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/common/utils/StringUtilsTests.java
> +        return Stream.of(
Почему нельзя было вокруг одно числа всё обставить? По факту первый и последний аргумент одинаковый по смыслу - оба больше чем maxLength

2021-08-13 13:46 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/controllercalls/ControllerCallsHistoryServiceSpringPgSqlContainerIT.java
> +    @DataSet(value = "ControllerCallDescriptionEntity.yml")
Во первых можно было аналогично поставить на уровень класса и был бы тот же самый эффект.
Во вторых - лучше сразу отучайся делать один датасет на класс. Изменишь для одного теста, посыпятся остальные, и тогда придется всё равно выносить. Поверь, много раз уже проверено

2021-08-13 13:46 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/controllercalls/ControllerCallsHistoryServiceSpringPgSqlContainerIT.java
> +        assertTrue(postgreSqlContainer.isRunning());
Тест на тестовое поле? Не нужно так делать. Сбивает с толку, т.к. в тестах, только рабочий код должен тестироваться

2021-08-13 13:46 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/rest/controllers/ControllerCallsHistoryControllerMvcIT.java
> +class ControllerCallsHistoryControllerMvcIT {
Бессмысленный тест в данном случае, т.к. просто проверяет только маппинг полей и что вызовется нужный метод.
Практически всегда контроллер минимальное кол-во логики, поэтому так тестить смысла нет, лучше сразу интеграционно. Тогда мы можем убедиться, что приложение работает на всём протяжении запроса

2021-08-13 13:46 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/controllercalls/ControllerCallsHistoryServiceSpringPgSqlContainerIT.java
> +class ControllerCallsHistoryServiceSpringPgSqlContainerIT {
До меня только сейчас дошло, а для чего IT на сервис, если всё равно будет точно такой же на контроллер (пока его не вижу, но он обязателен)?

2021-08-13 13:46 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/controllercalls/ControllerCallsHistoryLastCallsArgs.java
> +    private final String DATE_TIME_PATTERN = "yyyy-MM-dd HH:mm";
И для чего она тут? Если будет несколько дто, будет писать в каждом? Давай вынесем в конфиг какой-нибудь и пусть там лежит

2021-08-13 13:48 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/rest/actions/ControllerCallsHistoryActionTests.java
> +    private final LocalDateTime to   = LocalDateTime.parse("2020-01-01T12:00");
Некорректно выразился. Вопрос был про выравнивание кода. Ты его вручную так выравниваешь или как?

2021-08-13 13:49 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/common/utils/LocalDateTimeUtilsImpl.java
> +public class LocalDateTimeUtilsImpl implements LocalDateTimeUtils {
Нее, только не powerMock.
Используй Clock для этих целей. Т.е. создаешь бин Clock в конфиге, вносишь куда надо его и создаешь дату так LocalDateTime.now(clock). А в тестах (IT, Test) мокаешь методы clock и всё

2021-08-13 13:58 UTC, BlaBlaPrincess commented on src/test/java/com/blablaprincess/springboot_simplejava/rest/actions/ControllerCallsHistoryActionTests.java
> +    private final LocalDateTime to   = LocalDateTime.parse("2020-01-01T12:00");
Понял, да, вручную

2021-08-13 14:06 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/rest/controllers/ControllerCallsHistoryController.java
> +        return controllerCallsHistoryService.getLastCalls(args);
Да, согласен. В силу человеческого фактора, очень сложно вынести с занятий 100% того, что давали, и вот про querydsl я абсолютно забыл)

2021-08-13 14:37 UTC, BlaBlaPrincess commented on src/test/java/com/blablaprincess/springboot_simplejava/business/controllercalls/ControllerCallsHistoryServiceSpringPgSqlContainerIT.java
> +    @DataSet(value = "ControllerCallDescriptionEntity.yml")
Аннотацию поправил. Касательно второго - так у меня всего один тест)

2021-08-13 14:37 UTC, BlaBlaPrincess commented on src/test/java/com/blablaprincess/springboot_simplejava/business/controllercalls/ControllerCallsHistoryServiceSpringPgSqlContainerIT.java
> +    @DataSet(value = "ControllerCallDescriptionEntity.yml")
Но к сведению принял

2021-08-13 15:11 UTC, BlaBlaPrincess commented on src/test/java/com/blablaprincess/springboot_simplejava/rest/controllers/ControllerCallsHistoryControllerMvcIT.java
> +class ControllerCallsHistoryControllerMvcIT {
Объединил ControllerCallsHistoryControllerMvcIT и ControllerCallsHistoryServiceSpringPgSqlContainerIT

2021-08-13 15:26 UTC, BlaBlaPrincess commented on src/test/java/com/blablaprincess/springboot_simplejava/business/common/utils/StringUtilsTests.java
> +        return Stream.of(
Я думал как сделать лучше, а в итоге понял, что StringUtils работает неправильно, пусть и проходит все тесты, вот и сокращай их количество после) 
Класс починил, но вот тестов, вопреки conversation'у прибавил (плюс, заменил старые более читабельными), обосную каждый из них:

- `"123456", 7, "123456"` input меньше допустимой длины
- `"1234567", 7, "1234567"` input равен допустимой длине
- `"12345678", 7, "123…678"` input четной длины больше допустимой нечетной длины
- `"123456789", 7, "123…789"` input нечетной длины больше допустимой нечетной длины
- `"123456789", 8, "123…6789"` input нечетной длины больше допустимой четной длины
- `"1234567890", 8, "123…7890"` input четной длины больше допустимой четной длины

2021-08-13 15:56 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/business/controllercalls/ControllerCallsHistoryLastCallsArgs.java
> +    private final String DATE_TIME_PATTERN = "yyyy-MM-dd HH:mm";
Слово конфиг меня смущает, не знаю то ли имелось ввиду, но вынес в отдельный класс `DateTimeFormats`

2021-08-14 00:00 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/common/datetime/DateTimeFormats.java
> +    public static final String YEAR_TO_MINUTE = "yyyy-MM-dd HH:mm";
Почему название такое? Пусть будет просто DATE_FORMAT

2021-08-14 00:00 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/common/persistence/UuidEntity.java
> +            return Objects.equals(this.id, that.getId());
this тоже также

2021-08-14 00:00 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/common/utils/StringUtilsTests.java
> +        return Stream.of(
С таким обоснованием - отлично тогда

2021-08-14 00:00 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/rest/controllers/ControllerCallsHistoryControllerSpringPgSqlContainerIT.java
> +class ControllerCallsHistoryControllerSpringPgSqlContainerIT {
Для чего ты в название отражаешь SpringPgSqlContainer? При виде этого в тестах тебе это что-то принесет? Мне просто нет, поэтому спрашиваю

2021-08-14 00:00 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/rest/controllers/ControllerCallsHistoryControllerSpringPgSqlContainerIT.java
> +                .map(ControllerCallDescriptionEntity::getResponse)
А кто остальные поля будет проверять?
МОжно сделать так: 
- один тест без фильтров, но там проверяешь все поля
- параметризованный тест с фильтрами разными, но тут проверяешь, что-то уникальное (например, ты тут response проверяешь)

2021-08-14 00:04 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/controllercalls/ControllerCallsHistoryLastCallsArgs.java
> +    private final String DATE_TIME_PATTERN = "yyyy-MM-dd HH:mm";
Ну можно и так. Имел ввиду, что обычно есть AppConfig, в котором проставляем, например, всякие `@Enable...`. И вот в нём в принципе можно все такие константы вынести. Но можно и отдельный класс, как ты сделал
DateTimeFormat скорее всего будет один на весь сервис, так что выделять на него отдельный класс может показаться лишним

2021-08-14 00:04 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/rest/actions/ControllerCallsHistoryActionTests.java
> +    private final LocalDateTime to   = LocalDateTime.parse("2020-01-01T12:00");
Ну и для чего? Это же столько времени занимает, а толку от этого по нет

2021-08-14 00:05 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/common/persistence/UuidEntity.java
> +        return Objects.hash(this.id);
тоже через get

2021-08-14 00:08 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/common/utils/StringUtilsTests.java
> +        return Stream.of(
Только вот эти обоснования, да в пояснения к каждому набору параметров. Чтобы в следующий раз у других не возникло вопросов.
Не надо только прям расписывать это, только ключевые слова

2021-08-14 04:23 UTC, BlaBlaPrincess commented on src/test/java/com/blablaprincess/springboot_simplejava/rest/actions/ControllerCallsHistoryActionTests.java
> +    private final LocalDateTime to   = LocalDateTime.parse("2020-01-01T12:00");
Времени это не занимает, а читать проще. Так, наглядно видно, что `from` и `to` отличаются годом. В любом случае, вкусовщина

2021-08-14 04:47 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/business/common/datetime/DateTimeFormats.java
> +    public static final String YEAR_TO_MINUTE = "yyyy-MM-dd HH:mm";
Название DATE_FORMAT ничего не говорит о содержании

2021-08-14 04:49 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/business/common/persistence/UuidEntity.java
> +            return Objects.equals(this.id, that.getId());
Так ведь это обращение к своему полю, здесь не будет прокси

2021-08-14 04:51 UTC, BlaBlaPrincess commented on src/test/java/com/blablaprincess/springboot_simplejava/rest/controllers/ControllerCallsHistoryControllerSpringPgSqlContainerIT.java
> +class ControllerCallsHistoryControllerSpringPgSqlContainerIT {
Интеграционные тесты разные, я стараюсь отмечать их тип, так, например, есть `..MvcIT` и `..SpringIT`, хотя, в этой ветке, последние еще так не указаны

2021-08-14 04:59 UTC, BlaBlaPrincess commented on src/test/java/com/blablaprincess/springboot_simplejava/rest/controllers/ControllerCallsHistoryControllerSpringPgSqlContainerIT.java
> +                .map(ControllerCallDescriptionEntity::getResponse)
> один тест без фильтров, но там проверяешь все поля

Я правильно понимаю, что это тест на Entity?

2021-08-14 04:59 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/business/common/persistence/UuidEntity.java
> +        return Objects.hash(this.id);
[Аналогично](https://github.com/BlaBlaPrincess/WS-SpringBoot-SimpleJava/pull/4#discussion_r688863417)

2021-08-15 01:36 UTC, progressicu approved these changes
Мелочи поправишь, да и в принципе хорошо получилось

2021-08-15 01:36 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/common/datetime/DateTimeFormats.java
> +    public static final String YEAR_TO_MINUTE = "yyyy-MM-dd HH:mm";
Почему, говорит о том, какой формат даты принят в данном сервисе. Ну да ладно, больше придирки

2021-08-15 01:36 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/common/persistence/UuidEntity.java
> +            return Objects.equals(this.id, that.getId());
А с чего ты взял, что не будет прокси? Сущность инициализируется только при вызове getter-а, какого-либо поля, но не id. И пока она не проинициализируется, все поля null
https://blog.andrewbeacock.com/2008/08/how-to-implement-hibernate-safe-equals.html

Если по простому, то это как-то так выглядит (по крайней мере раньше)
```
public class HibernateProxy extends MyEntity {
    private MyEntity target;
    private UUID identificator; //not id!

    public String getId() {
       return identificator;
    }

    public String getFirstName() {
        if (target == null) {
            target = readFromDatabase();
        }
        return target.getFirstName();
    }
}
```

2021-08-15 01:36 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/common/utils/StringUtilsTests.java
> +        return Stream.of(
Я думал, что ты их в названия тестов засунешь. Когда запускаешь тест, ты увидишь: "123456 input length, 7 max length". И вот мне как то не несет особого смысла, что на вход подается и какая длина. А вот "input < maxLength" было бы действительно познавательно

2021-08-15 01:36 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/rest/controllers/ControllerCallsHistoryControllerSpringPgSqlContainerIT.java
> +class ControllerCallsHistoryControllerSpringPgSqlContainerIT {
Хм, действтительно. Сразу как-то не заметил. Довольно интересная вещь получается. Можно это заиспользовать даже, чтобы запускались только определенные интеграционные тесты
Ок

2021-08-15 01:36 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/rest/controllers/ControllerCallsHistoryControllerSpringPgSqlContainerIT.java
> +        entity.setId(UUID.fromString("10000000-1000-1000-9000-900000000000"));
Чтобы так не делать, посмотри `@SuperBuilder` из lombok

2021-08-15 01:36 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/rest/controllers/ControllerCallsHistoryControllerSpringPgSqlContainerIT.java
> +                .map(ControllerCallDescriptionEntity::getResponse)
В каком смысле на Entity, а то не совсем понял?
Ну сейчас у тебя хорошо получилось

2021-08-15 02:09 UTC, BlaBlaPrincess commented on src/test/java/com/blablaprincess/springboot_simplejava/rest/controllers/ControllerCallsHistoryControllerSpringPgSqlContainerIT.java
> +                .map(ControllerCallDescriptionEntity::getResponse)
Я имел ввиду, что если мы в тесте проверяем все поля, то единственный выигрыш, относительна теста, где мы бы проверяли лишь одно поле, в проверке того, что Entity (особенно, если оно сложное) правильно подтягивает все значения из БД. Я так предполагаю, что тест нужен за этим

2021-08-15 02:09 UTC, merged

2021-08-15 02:31 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/rest/controllers/ControllerCallsHistoryControllerSpringPgSqlContainerIT.java
> +                .map(ControllerCallDescriptionEntity::getResponse)
Обычно нет. 
Это нужно, чтобы проверить, что правильно всё маппится в дто, которых хотя у тебя нет, но они должны быть. Ну и просто нужно всегда проверить правильность всех полей хотя бы в одном тесте