Add telegram bot notifier
BlaBlaPrincess/WS-SpringBoot-SimpleJava pull request #5
Opened 2021-08-07 05:41 UTC by BlaBlaPrincess

2021-08-10 07:59 UTC, progressicu requested changes

2021-08-10 07:59 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/notifiers/telegram/TelegramBotNotifierService.java
> +        HTTP_TOKEN = environment.getRequiredProperty("telegram-bot.http-token");
Через @Value

2021-08-10 07:59 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/notifiers/telegram/TelegramBotNotifierService.java
> +        try (CloseableHttpClient client = HttpClients.createDefault()) {
Чтобы каждый раз такое не писать, можно заиспользовать что-нибудь из spring-а. Например, webCLient

2021-08-10 07:59 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/notifiers/telegram/TelegramBotNotifierService.java
> +public class TelegramBotNotifierService implements Notifier {
Где на него тест?

2021-08-10 07:59 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/notifiers/Notifier.java
> +    void sendNotification(String message);
Это вообще где-то вызывается?

2021-08-12 09:05 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/business/notifiers/Notifier.java
> +    void sendNotification(String message);
Нет, только в следующем pr, который про аннотации

2021-08-13 14:03 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/notifiers/telegram/TelegramBotNotifierService.java
> +        HTTP_TOKEN = httpToken;
Почему с большой буквы названия полей?

2021-08-13 14:03 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/notifiers/telegram/TelegramBotNotifierService.java
> +    public TelegramBotNotifierService(@Value("${telegram-bot.http-token}") String httpToken,
Можно было добавить lombok.config, который скидывали в группу. Тогда можно было бы эти аннотации поставить над полем, а над классом @RequiredArgConstructor и всё

2021-08-13 14:03 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/notifiers/telegram/TelegramBotNotifierService.java
> +        SEND_MESSAGE_TEMPLATE = String.format("https://api.telegram.org/bot%s/sendMessage?chat_id=%s&text={message}", HTTP_TOKEN, CHAT_ID);
Тем более для чего тебе переменные, если ты сразу делаешь данную строку

2021-08-13 14:03 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/notifiers/telegram/TelegramBotNotifierService.java
> +              .bodyToMono(JsonNode.class)
JsonNode?

2021-08-13 14:03 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/notifiers/telegram/TelegramBotNotifierService.java
> +        log.warn(String.format("Telegram notification failed. Cause: %s (%s)", e.getCause(), e.getMessage()));
не совсем то, что тебе нужно. Тут нужно было log.error(message, e). Тогда весь stacktrace пропишется в лог, а так только причина (которая еще не всегда есть)

2021-08-13 14:03 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/validation/integers/MaxLengthValidator.java
>  @PropertySource("classpath:application.properties")
Не нужно, т.к. эти проперти и так загружаются

2021-08-13 14:03 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/notifiers/telegram/TelegramBotNotifierServiceTests.java
> +        verify(exchangeFunction).exchange(any());
И что ты тут проверил? Что просто метод вызвался? Если так писать, то мы только на тестах и будем сидеть

2021-08-13 14:03 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/notifiers/telegram/TelegramBotNotifierServiceTests.java
> +        verify(exchangeFunction).exchange(any());
Ты почему то пишешь ненужные тесты, а нужные пропускаешь

2021-08-13 14:03 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/validation/integers/MaxLengthValidatorTests.java
> +        assertDoesNotThrow(() -> new MaxLengthValidator(maxLength).validate(value));
Ну и опять. Для чего ты задаешь эту длину разную. Поставь одну и всё, меньше тестов, меньше думать, меньше проблем

2021-08-13 16:10 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/business/notifiers/telegram/TelegramBotNotifierService.java
> +    public TelegramBotNotifierService(@Value("${telegram-bot.http-token}") String httpToken,
Мне кажется, ты о другом. Здесь [вот  это](https://stackoverflow.com/questions/7130425/spring-property-injection-in-a-final-attribute-value-java)

2021-08-13 16:26 UTC, BlaBlaPrincess commented on src/test/java/com/blablaprincess/springboot_simplejava/business/notifiers/telegram/TelegramBotNotifierServiceTests.java
> +        verify(exchangeFunction).exchange(any());
Ты [спросил](https://github.com/BlaBlaPrincess/WS-SpringBoot-SimpleJava/pull/5#discussion_r685783708) где тесты на этот класс. Не знаю, что еще можно здесь протестировать

2021-08-13 16:29 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/business/validation/integers/MaxLengthValidator.java
>  @PropertySource("classpath:application.properties")
Починил. Интересно, с чего это git предложил этот класс на ревью) его нет в пр.

2021-08-13 17:22 UTC, BlaBlaPrincess commented on src/test/java/com/blablaprincess/springboot_simplejava/business/validation/integers/MaxLengthValidatorTests.java
> +        assertDoesNotThrow(() -> new MaxLengthValidator(maxLength).validate(value));
Я мыслю так, что если тестировать одну длину, то это не репрезентативно, так как может быть совпадением, хотя бы два кейса, уже почти гарантируют, что это не случайность.

2021-08-13 17:28 UTC, BlaBlaPrincess commented on src/main/java/com/blablaprincess/springboot_simplejava/business/notifiers/telegram/TelegramBotNotifierService.java
> +              .bodyToMono(JsonNode.class)
Заменил на `toBodilessEntity()`. А так, если я правильно понял принцип работы, `JsonNode` подходит, когда нужно распарсить поля json'а без привязки к конкретному классу. Я не обратил внимания на  `toBodilessEntity()` и рассудил, что это неплохое решение

2021-08-14 00:14 UTC, progressicu commented on pom.xml
>  			<artifactId>reflections</artifactId>
А для чего тебе тут эта либа?

2021-08-14 00:14 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/notifiers/telegram/TelegramBotNotifierService.java
> +    public TelegramBotNotifierService(@Value("${telegram-bot.http-token}") String httpToken,
Нет, как раз об этом, чтобы меньше конструкторов писать.
[Здесь](https://stackoverflow.com/questions/52321988/best-practice-for-value-fields-lombok-and-constructor-injection) оба ответа почитай

2021-08-14 00:14 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/notifiers/telegram/TelegramBotNotifierServiceTests.java
> +        verify(exchangeFunction).exchange(any());
Протестировать, что вызвался с правильным uri, токеном, текстом и т.п.

2021-08-14 00:14 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/validation/integers/MaxLengthValidatorTests.java
> +        assertDoesNotThrow(() -> new MaxLengthValidator(maxLength).validate(value));
В каком смысле совпадение?

2021-08-14 00:18 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/notifiers/telegram/TelegramBotNotifierService.java
> +              .bodyToMono(JsonNode.class)
Ну ты же не парсил ответ, а просто "fire and forget". Так что тут подошло как ты сейчас сделал (надеюсь, что работает, т.к. с `toBodilessEntity()` ни разу не встречался), либо просто bodyToMono(Void.class)

2021-08-14 05:31 UTC, BlaBlaPrincess commented on pom.xml
>  			<artifactId>reflections</artifactId>
Используется в тестах на ExceptionHandler, добавил scope test

2021-08-14 05:40 UTC, BlaBlaPrincess commented on src/test/java/com/blablaprincess/springboot_simplejava/business/validation/integers/MaxLengthValidatorTests.java
> +        assertDoesNotThrow(() -> new MaxLengthValidator(maxLength).validate(value));
Очень грубо, но например, если бы я что нибудь такое написал

![image](https://user-images.githubusercontent.com/66216611/129435346-36fd2361-701f-4c82-8414-2d6d4b858d9b.png)

И после тестировал с длиной 8

2021-08-14 05:43 UTC, BlaBlaPrincess commented on src/test/java/com/blablaprincess/springboot_simplejava/business/validation/integers/MaxLengthValidatorTests.java
> +        assertDoesNotThrow(() -> new MaxLengthValidator(maxLength).validate(value));
Или, менее грубый пример из соседнего pr, тесты на `StringUtils` с четной длиной input работали, а с нечетной нет

2021-08-15 01:51 UTC, progressicu commented on src/main/java/com/blablaprincess/springboot_simplejava/business/notifiers/telegram/TelegramBotNotifierService.java
> +    private final String messageHttpRequestTemplate;
Когда написал, что зачем тебе переменные, я не это имел ввиду.
Да, это должно работать вроде, но смотрится не очень, как по мне. С  sendMessageTemplate смотрелось лучше, когда через String.format внедрял параметры в конструкторе

2021-08-15 01:51 UTC, progressicu commented on src/test/java/com/blablaprincess/springboot_simplejava/business/notifiers/telegram/TelegramBotNotifierServiceTests.java
> +        TelegramBotNotifierService service = new TelegramBotNotifierService(messageHttpRequestTemplate, webClient);
- Тестируемый класс желательно должен быть как поле тестового класса
- Наверное было бы чище, если сделать через [mock WebCLient-а](https://github.com/Rapadapl/TheWhiteHomework-Back-Console/pull/5/files#diff-c6e968ee9afe89c9e6f076801c00991f2922fee28f71c4ccc229ea424786a56fR29), либо через [mock server](https://github.com/MV-shallow/NumberStats/blob/master/src/test/java/org/thewhite/notification/service/TelegramNotifierTest.java).
Просто в данном случае у тебя переплетаются act, assert, arrange.

2021-08-15 01:52 UTC, progressicu approved these changes

2021-08-15 03:16 UTC, merged